# Where should we write the GIF?
Output ./examples/demo.gif

# Set up a terminal with font size
Set Shell bash
Set FontSize 18
Set Width 1200
Set Height 800
Set TypingSpeed 150ms
#Set Theme "Catppuccin Macchiato"

Sleep 500ms
Type "go run main.go"
Sleep 500ms
Enter
Sleep 1s
Type "jjkk"
Sleep 500ms
Enter
Sleep 2s
Type "b"
#Screenshot ./examples/screenshot.png
Sleep 1s
Type "3"
Sleep 2s
Type ":config"
Enter
Sleep 2s
Type ":home"
Enter
Sleep 1ms
Type ":q"
Enter
Sleep 500ms
